version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: todo-db
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "7.4"
    container_name: todo-backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    env_file:
      - backend/.env.docker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile      
    container_name: todo-frontend
    working_dir: /app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      HOST: 0.0.0.0
      VUE_APP_API_BASE: http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  db_data:

networks:
  default:
    name: desafio_mario_net